# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x0f\x43hatsApp.common\"9\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x13\n\x0b\x64isplayname\x18\x03 \x01(\t\"!\n\x05Group\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"?\n\x0bMessageUser\x12\x0e\n\x06userid\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0e\n\x06sentat\x18\x03 \x01(\t*z\n\x0eResponseStatus\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\x12\x11\n\rINVALID_INPUT\x10\x02\x12\x12\n\x0e\x41\x43\x43OUNT_EXISTS\x10\x03\x12\x15\n\x11\x41\x43\x43OUNT_NOT_FOUND\x10\x04\x12\x10\n\x0cUNAUTHORIZED\x10\x05*A\n\rMessageStatus\x12\r\n\tDELIVERED\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x12\x0b\n\x07PENDING\x10\x02\x12\x08\n\x04READ\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESPONSESTATUS']._serialized_start=192
  _globals['_RESPONSESTATUS']._serialized_end=314
  _globals['_MESSAGESTATUS']._serialized_start=316
  _globals['_MESSAGESTATUS']._serialized_end=381
  _globals['_USER']._serialized_start=33
  _globals['_USER']._serialized_end=90
  _globals['_GROUP']._serialized_start=92
  _globals['_GROUP']._serialized_end=125
  _globals['_MESSAGEUSER']._serialized_start=127
  _globals['_MESSAGEUSER']._serialized_end=190
# @@protoc_insertion_point(module_scope)
