# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: groups.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'groups.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cgroups.proto\x12\x0e\x43hatsApp.group\x1a\x0c\x63ommon.proto\"U\n\x12LoadMessageRequest\x12.\n\x08\x66romuser\x18\x01 \x01(\x0b\x32\x1c.ChatsApp.common.MessageUser\x12\x0f\n\x07groupid\x18\x02 \x01(\x05\"\x97\x01\n\x13LoadMessageResponse\x12,\n\x06sender\x18\x01 \x03(\x0b\x32\x1c.ChatsApp.common.MessageUser\x12.\n\x08receiver\x18\x02 \x03(\x0b\x32\x1c.ChatsApp.common.MessageUser\x12\x0f\n\x07message\x18\x03 \x03(\t\x12\x11\n\ttimestamp\x18\x04 \x03(\t\"G\n\x15ReceiveMessageRequest\x12.\n\x08\x66romuser\x18\x01 \x01(\x0b\x32\x1c.ChatsApp.common.MessageUser\"n\n\x16ReceiveMessageResponse\x12.\n\x08\x66romuser\x18\x01 \x01(\x0b\x32\x1c.ChatsApp.common.MessageUser\x12\x13\n\x0btextmessage\x18\x02 \x01(\t\x12\x0f\n\x07groupid\x18\x03 \x01(\x05\"j\n\x12SendMessageRequest\x12.\n\x08\x66romuser\x18\x01 \x01(\x0b\x32\x1c.ChatsApp.common.MessageUser\x12\x0f\n\x07groupid\x18\x02 \x01(\x05\x12\x13\n\x0btextmessage\x18\x03 \x01(\t\"O\n\x13SendMessageResponse\x12\x38\n\x08response\x18\x01 \x01(\x0e\x32&.ChatsApp.common.MessageResponseStatus2\xda\x01\n\x0fUserChatService\x12^\n\x0fSendUserMessage\x12\".ChatsApp.group.SendMessageRequest\x1a#.ChatsApp.group.SendMessageResponse(\x01\x30\x01\x12g\n\x12ReceiveUserMessage\x12%.ChatsApp.group.ReceiveMessageRequest\x1a&.ChatsApp.group.ReceiveMessageResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'groups_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOADMESSAGEREQUEST']._serialized_start=46
  _globals['_LOADMESSAGEREQUEST']._serialized_end=131
  _globals['_LOADMESSAGERESPONSE']._serialized_start=134
  _globals['_LOADMESSAGERESPONSE']._serialized_end=285
  _globals['_RECEIVEMESSAGEREQUEST']._serialized_start=287
  _globals['_RECEIVEMESSAGEREQUEST']._serialized_end=358
  _globals['_RECEIVEMESSAGERESPONSE']._serialized_start=360
  _globals['_RECEIVEMESSAGERESPONSE']._serialized_end=470
  _globals['_SENDMESSAGEREQUEST']._serialized_start=472
  _globals['_SENDMESSAGEREQUEST']._serialized_end=578
  _globals['_SENDMESSAGERESPONSE']._serialized_start=580
  _globals['_SENDMESSAGERESPONSE']._serialized_end=659
  _globals['_USERCHATSERVICE']._serialized_start=662
  _globals['_USERCHATSERVICE']._serialized_end=880
# @@protoc_insertion_point(module_scope)
