// source: groups.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var common_pb = require('./common_pb.js');
goog.object.extend(proto, common_pb);
goog.exportSymbol('proto.ChatsApp.group.LoadMessageRequest', null, global);
goog.exportSymbol('proto.ChatsApp.group.LoadMessageResponse', null, global);
goog.exportSymbol('proto.ChatsApp.group.ReceiveMessageRequest', null, global);
goog.exportSymbol('proto.ChatsApp.group.ReceiveMessageResponse', null, global);
goog.exportSymbol('proto.ChatsApp.group.SendMessageRequest', null, global);
goog.exportSymbol('proto.ChatsApp.group.SendMessageResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ChatsApp.group.LoadMessageRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ChatsApp.group.LoadMessageRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ChatsApp.group.LoadMessageRequest.displayName = 'proto.ChatsApp.group.LoadMessageRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ChatsApp.group.LoadMessageResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ChatsApp.group.LoadMessageResponse.repeatedFields_, null);
};
goog.inherits(proto.ChatsApp.group.LoadMessageResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ChatsApp.group.LoadMessageResponse.displayName = 'proto.ChatsApp.group.LoadMessageResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ChatsApp.group.ReceiveMessageRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ChatsApp.group.ReceiveMessageRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ChatsApp.group.ReceiveMessageRequest.displayName = 'proto.ChatsApp.group.ReceiveMessageRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ChatsApp.group.ReceiveMessageResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ChatsApp.group.ReceiveMessageResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ChatsApp.group.ReceiveMessageResponse.displayName = 'proto.ChatsApp.group.ReceiveMessageResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ChatsApp.group.SendMessageRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ChatsApp.group.SendMessageRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ChatsApp.group.SendMessageRequest.displayName = 'proto.ChatsApp.group.SendMessageRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ChatsApp.group.SendMessageResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ChatsApp.group.SendMessageResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ChatsApp.group.SendMessageResponse.displayName = 'proto.ChatsApp.group.SendMessageResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ChatsApp.group.LoadMessageRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.ChatsApp.group.LoadMessageRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ChatsApp.group.LoadMessageRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ChatsApp.group.LoadMessageRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    fromuser: (f = msg.getFromuser()) && common_pb.MessageUser.toObject(includeInstance, f),
    groupid: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ChatsApp.group.LoadMessageRequest}
 */
proto.ChatsApp.group.LoadMessageRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ChatsApp.group.LoadMessageRequest;
  return proto.ChatsApp.group.LoadMessageRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ChatsApp.group.LoadMessageRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ChatsApp.group.LoadMessageRequest}
 */
proto.ChatsApp.group.LoadMessageRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new common_pb.MessageUser;
      reader.readMessage(value,common_pb.MessageUser.deserializeBinaryFromReader);
      msg.setFromuser(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setGroupid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ChatsApp.group.LoadMessageRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ChatsApp.group.LoadMessageRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ChatsApp.group.LoadMessageRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ChatsApp.group.LoadMessageRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFromuser();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      common_pb.MessageUser.serializeBinaryToWriter
    );
  }
  f = message.getGroupid();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * optional ChatsApp.common.MessageUser fromuser = 1;
 * @return {?proto.ChatsApp.common.MessageUser}
 */
proto.ChatsApp.group.LoadMessageRequest.prototype.getFromuser = function() {
  return /** @type{?proto.ChatsApp.common.MessageUser} */ (
    jspb.Message.getWrapperField(this, common_pb.MessageUser, 1));
};


/**
 * @param {?proto.ChatsApp.common.MessageUser|undefined} value
 * @return {!proto.ChatsApp.group.LoadMessageRequest} returns this
*/
proto.ChatsApp.group.LoadMessageRequest.prototype.setFromuser = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ChatsApp.group.LoadMessageRequest} returns this
 */
proto.ChatsApp.group.LoadMessageRequest.prototype.clearFromuser = function() {
  return this.setFromuser(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ChatsApp.group.LoadMessageRequest.prototype.hasFromuser = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 groupid = 2;
 * @return {number}
 */
proto.ChatsApp.group.LoadMessageRequest.prototype.getGroupid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.ChatsApp.group.LoadMessageRequest} returns this
 */
proto.ChatsApp.group.LoadMessageRequest.prototype.setGroupid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ChatsApp.group.LoadMessageResponse.repeatedFields_ = [1,2,3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ChatsApp.group.LoadMessageResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.ChatsApp.group.LoadMessageResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ChatsApp.group.LoadMessageResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ChatsApp.group.LoadMessageResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    senderList: jspb.Message.toObjectList(msg.getSenderList(),
    common_pb.MessageUser.toObject, includeInstance),
    receiverList: jspb.Message.toObjectList(msg.getReceiverList(),
    common_pb.MessageUser.toObject, includeInstance),
    messageList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    timestampList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ChatsApp.group.LoadMessageResponse}
 */
proto.ChatsApp.group.LoadMessageResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ChatsApp.group.LoadMessageResponse;
  return proto.ChatsApp.group.LoadMessageResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ChatsApp.group.LoadMessageResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ChatsApp.group.LoadMessageResponse}
 */
proto.ChatsApp.group.LoadMessageResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new common_pb.MessageUser;
      reader.readMessage(value,common_pb.MessageUser.deserializeBinaryFromReader);
      msg.addSender(value);
      break;
    case 2:
      var value = new common_pb.MessageUser;
      reader.readMessage(value,common_pb.MessageUser.deserializeBinaryFromReader);
      msg.addReceiver(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addMessage(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.addTimestamp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ChatsApp.group.LoadMessageResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ChatsApp.group.LoadMessageResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ChatsApp.group.LoadMessageResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ChatsApp.group.LoadMessageResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSenderList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      common_pb.MessageUser.serializeBinaryToWriter
    );
  }
  f = message.getReceiverList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      common_pb.MessageUser.serializeBinaryToWriter
    );
  }
  f = message.getMessageList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getTimestampList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      4,
      f
    );
  }
};


/**
 * repeated ChatsApp.common.MessageUser sender = 1;
 * @return {!Array<!proto.ChatsApp.common.MessageUser>}
 */
proto.ChatsApp.group.LoadMessageResponse.prototype.getSenderList = function() {
  return /** @type{!Array<!proto.ChatsApp.common.MessageUser>} */ (
    jspb.Message.getRepeatedWrapperField(this, common_pb.MessageUser, 1));
};


/**
 * @param {!Array<!proto.ChatsApp.common.MessageUser>} value
 * @return {!proto.ChatsApp.group.LoadMessageResponse} returns this
*/
proto.ChatsApp.group.LoadMessageResponse.prototype.setSenderList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.ChatsApp.common.MessageUser=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ChatsApp.common.MessageUser}
 */
proto.ChatsApp.group.LoadMessageResponse.prototype.addSender = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.ChatsApp.common.MessageUser, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ChatsApp.group.LoadMessageResponse} returns this
 */
proto.ChatsApp.group.LoadMessageResponse.prototype.clearSenderList = function() {
  return this.setSenderList([]);
};


/**
 * repeated ChatsApp.common.MessageUser receiver = 2;
 * @return {!Array<!proto.ChatsApp.common.MessageUser>}
 */
proto.ChatsApp.group.LoadMessageResponse.prototype.getReceiverList = function() {
  return /** @type{!Array<!proto.ChatsApp.common.MessageUser>} */ (
    jspb.Message.getRepeatedWrapperField(this, common_pb.MessageUser, 2));
};


/**
 * @param {!Array<!proto.ChatsApp.common.MessageUser>} value
 * @return {!proto.ChatsApp.group.LoadMessageResponse} returns this
*/
proto.ChatsApp.group.LoadMessageResponse.prototype.setReceiverList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.ChatsApp.common.MessageUser=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ChatsApp.common.MessageUser}
 */
proto.ChatsApp.group.LoadMessageResponse.prototype.addReceiver = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.ChatsApp.common.MessageUser, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ChatsApp.group.LoadMessageResponse} returns this
 */
proto.ChatsApp.group.LoadMessageResponse.prototype.clearReceiverList = function() {
  return this.setReceiverList([]);
};


/**
 * repeated string message = 3;
 * @return {!Array<string>}
 */
proto.ChatsApp.group.LoadMessageResponse.prototype.getMessageList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.ChatsApp.group.LoadMessageResponse} returns this
 */
proto.ChatsApp.group.LoadMessageResponse.prototype.setMessageList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.ChatsApp.group.LoadMessageResponse} returns this
 */
proto.ChatsApp.group.LoadMessageResponse.prototype.addMessage = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ChatsApp.group.LoadMessageResponse} returns this
 */
proto.ChatsApp.group.LoadMessageResponse.prototype.clearMessageList = function() {
  return this.setMessageList([]);
};


/**
 * repeated string timestamp = 4;
 * @return {!Array<string>}
 */
proto.ChatsApp.group.LoadMessageResponse.prototype.getTimestampList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.ChatsApp.group.LoadMessageResponse} returns this
 */
proto.ChatsApp.group.LoadMessageResponse.prototype.setTimestampList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.ChatsApp.group.LoadMessageResponse} returns this
 */
proto.ChatsApp.group.LoadMessageResponse.prototype.addTimestamp = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ChatsApp.group.LoadMessageResponse} returns this
 */
proto.ChatsApp.group.LoadMessageResponse.prototype.clearTimestampList = function() {
  return this.setTimestampList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ChatsApp.group.ReceiveMessageRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.ChatsApp.group.ReceiveMessageRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ChatsApp.group.ReceiveMessageRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ChatsApp.group.ReceiveMessageRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    fromuser: (f = msg.getFromuser()) && common_pb.MessageUser.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ChatsApp.group.ReceiveMessageRequest}
 */
proto.ChatsApp.group.ReceiveMessageRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ChatsApp.group.ReceiveMessageRequest;
  return proto.ChatsApp.group.ReceiveMessageRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ChatsApp.group.ReceiveMessageRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ChatsApp.group.ReceiveMessageRequest}
 */
proto.ChatsApp.group.ReceiveMessageRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new common_pb.MessageUser;
      reader.readMessage(value,common_pb.MessageUser.deserializeBinaryFromReader);
      msg.setFromuser(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ChatsApp.group.ReceiveMessageRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ChatsApp.group.ReceiveMessageRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ChatsApp.group.ReceiveMessageRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ChatsApp.group.ReceiveMessageRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFromuser();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      common_pb.MessageUser.serializeBinaryToWriter
    );
  }
};


/**
 * optional ChatsApp.common.MessageUser fromuser = 1;
 * @return {?proto.ChatsApp.common.MessageUser}
 */
proto.ChatsApp.group.ReceiveMessageRequest.prototype.getFromuser = function() {
  return /** @type{?proto.ChatsApp.common.MessageUser} */ (
    jspb.Message.getWrapperField(this, common_pb.MessageUser, 1));
};


/**
 * @param {?proto.ChatsApp.common.MessageUser|undefined} value
 * @return {!proto.ChatsApp.group.ReceiveMessageRequest} returns this
*/
proto.ChatsApp.group.ReceiveMessageRequest.prototype.setFromuser = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ChatsApp.group.ReceiveMessageRequest} returns this
 */
proto.ChatsApp.group.ReceiveMessageRequest.prototype.clearFromuser = function() {
  return this.setFromuser(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ChatsApp.group.ReceiveMessageRequest.prototype.hasFromuser = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ChatsApp.group.ReceiveMessageResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.ChatsApp.group.ReceiveMessageResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ChatsApp.group.ReceiveMessageResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ChatsApp.group.ReceiveMessageResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    fromuser: (f = msg.getFromuser()) && common_pb.MessageUser.toObject(includeInstance, f),
    textmessage: jspb.Message.getFieldWithDefault(msg, 2, ""),
    groupid: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ChatsApp.group.ReceiveMessageResponse}
 */
proto.ChatsApp.group.ReceiveMessageResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ChatsApp.group.ReceiveMessageResponse;
  return proto.ChatsApp.group.ReceiveMessageResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ChatsApp.group.ReceiveMessageResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ChatsApp.group.ReceiveMessageResponse}
 */
proto.ChatsApp.group.ReceiveMessageResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new common_pb.MessageUser;
      reader.readMessage(value,common_pb.MessageUser.deserializeBinaryFromReader);
      msg.setFromuser(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTextmessage(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setGroupid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ChatsApp.group.ReceiveMessageResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ChatsApp.group.ReceiveMessageResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ChatsApp.group.ReceiveMessageResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ChatsApp.group.ReceiveMessageResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFromuser();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      common_pb.MessageUser.serializeBinaryToWriter
    );
  }
  f = message.getTextmessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getGroupid();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * optional ChatsApp.common.MessageUser fromuser = 1;
 * @return {?proto.ChatsApp.common.MessageUser}
 */
proto.ChatsApp.group.ReceiveMessageResponse.prototype.getFromuser = function() {
  return /** @type{?proto.ChatsApp.common.MessageUser} */ (
    jspb.Message.getWrapperField(this, common_pb.MessageUser, 1));
};


/**
 * @param {?proto.ChatsApp.common.MessageUser|undefined} value
 * @return {!proto.ChatsApp.group.ReceiveMessageResponse} returns this
*/
proto.ChatsApp.group.ReceiveMessageResponse.prototype.setFromuser = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ChatsApp.group.ReceiveMessageResponse} returns this
 */
proto.ChatsApp.group.ReceiveMessageResponse.prototype.clearFromuser = function() {
  return this.setFromuser(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ChatsApp.group.ReceiveMessageResponse.prototype.hasFromuser = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string textmessage = 2;
 * @return {string}
 */
proto.ChatsApp.group.ReceiveMessageResponse.prototype.getTextmessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ChatsApp.group.ReceiveMessageResponse} returns this
 */
proto.ChatsApp.group.ReceiveMessageResponse.prototype.setTextmessage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 groupid = 3;
 * @return {number}
 */
proto.ChatsApp.group.ReceiveMessageResponse.prototype.getGroupid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.ChatsApp.group.ReceiveMessageResponse} returns this
 */
proto.ChatsApp.group.ReceiveMessageResponse.prototype.setGroupid = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ChatsApp.group.SendMessageRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.ChatsApp.group.SendMessageRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ChatsApp.group.SendMessageRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ChatsApp.group.SendMessageRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    fromuser: (f = msg.getFromuser()) && common_pb.MessageUser.toObject(includeInstance, f),
    groupid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    textmessage: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ChatsApp.group.SendMessageRequest}
 */
proto.ChatsApp.group.SendMessageRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ChatsApp.group.SendMessageRequest;
  return proto.ChatsApp.group.SendMessageRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ChatsApp.group.SendMessageRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ChatsApp.group.SendMessageRequest}
 */
proto.ChatsApp.group.SendMessageRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new common_pb.MessageUser;
      reader.readMessage(value,common_pb.MessageUser.deserializeBinaryFromReader);
      msg.setFromuser(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setGroupid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTextmessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ChatsApp.group.SendMessageRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ChatsApp.group.SendMessageRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ChatsApp.group.SendMessageRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ChatsApp.group.SendMessageRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFromuser();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      common_pb.MessageUser.serializeBinaryToWriter
    );
  }
  f = message.getGroupid();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getTextmessage();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional ChatsApp.common.MessageUser fromuser = 1;
 * @return {?proto.ChatsApp.common.MessageUser}
 */
proto.ChatsApp.group.SendMessageRequest.prototype.getFromuser = function() {
  return /** @type{?proto.ChatsApp.common.MessageUser} */ (
    jspb.Message.getWrapperField(this, common_pb.MessageUser, 1));
};


/**
 * @param {?proto.ChatsApp.common.MessageUser|undefined} value
 * @return {!proto.ChatsApp.group.SendMessageRequest} returns this
*/
proto.ChatsApp.group.SendMessageRequest.prototype.setFromuser = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ChatsApp.group.SendMessageRequest} returns this
 */
proto.ChatsApp.group.SendMessageRequest.prototype.clearFromuser = function() {
  return this.setFromuser(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ChatsApp.group.SendMessageRequest.prototype.hasFromuser = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 groupid = 2;
 * @return {number}
 */
proto.ChatsApp.group.SendMessageRequest.prototype.getGroupid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.ChatsApp.group.SendMessageRequest} returns this
 */
proto.ChatsApp.group.SendMessageRequest.prototype.setGroupid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string textmessage = 3;
 * @return {string}
 */
proto.ChatsApp.group.SendMessageRequest.prototype.getTextmessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.ChatsApp.group.SendMessageRequest} returns this
 */
proto.ChatsApp.group.SendMessageRequest.prototype.setTextmessage = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ChatsApp.group.SendMessageResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.ChatsApp.group.SendMessageResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ChatsApp.group.SendMessageResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ChatsApp.group.SendMessageResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    response: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ChatsApp.group.SendMessageResponse}
 */
proto.ChatsApp.group.SendMessageResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ChatsApp.group.SendMessageResponse;
  return proto.ChatsApp.group.SendMessageResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ChatsApp.group.SendMessageResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ChatsApp.group.SendMessageResponse}
 */
proto.ChatsApp.group.SendMessageResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.ChatsApp.common.MessageResponseStatus} */ (reader.readEnum());
      msg.setResponse(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ChatsApp.group.SendMessageResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ChatsApp.group.SendMessageResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ChatsApp.group.SendMessageResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ChatsApp.group.SendMessageResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResponse();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
};


/**
 * optional ChatsApp.common.MessageResponseStatus response = 1;
 * @return {!proto.ChatsApp.common.MessageResponseStatus}
 */
proto.ChatsApp.group.SendMessageResponse.prototype.getResponse = function() {
  return /** @type {!proto.ChatsApp.common.MessageResponseStatus} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.ChatsApp.common.MessageResponseStatus} value
 * @return {!proto.ChatsApp.group.SendMessageResponse} returns this
 */
proto.ChatsApp.group.SendMessageResponse.prototype.setResponse = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


goog.object.extend(exports, proto.ChatsApp.group);
