# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import groups_pb2 as groups__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in groups_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GroupChatServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LoadMessages = channel.unary_unary(
                '/ChatsApp.group.GroupChatService/LoadMessages',
                request_serializer=groups__pb2.LoadMessageRequest.SerializeToString,
                response_deserializer=groups__pb2.LoadMessageResponse.FromString,
                _registered_method=True)
        self.SendMessage = channel.stream_stream(
                '/ChatsApp.group.GroupChatService/SendMessage',
                request_serializer=groups__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=groups__pb2.SendMessageResponse.FromString,
                _registered_method=True)
        self.ReceiveMessages = channel.stream_stream(
                '/ChatsApp.group.GroupChatService/ReceiveMessages',
                request_serializer=groups__pb2.ReceiveMessageRequest.SerializeToString,
                response_deserializer=groups__pb2.ReceiveMessageResponse.FromString,
                _registered_method=True)


class GroupChatServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LoadMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveMessages(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GroupChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LoadMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadMessages,
                    request_deserializer=groups__pb2.LoadMessageRequest.FromString,
                    response_serializer=groups__pb2.LoadMessageResponse.SerializeToString,
            ),
            'SendMessage': grpc.stream_stream_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=groups__pb2.SendMessageRequest.FromString,
                    response_serializer=groups__pb2.SendMessageResponse.SerializeToString,
            ),
            'ReceiveMessages': grpc.stream_stream_rpc_method_handler(
                    servicer.ReceiveMessages,
                    request_deserializer=groups__pb2.ReceiveMessageRequest.FromString,
                    response_serializer=groups__pb2.ReceiveMessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ChatsApp.group.GroupChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ChatsApp.group.GroupChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GroupChatService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LoadMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ChatsApp.group.GroupChatService/LoadMessages',
            groups__pb2.LoadMessageRequest.SerializeToString,
            groups__pb2.LoadMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessage(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ChatsApp.group.GroupChatService/SendMessage',
            groups__pb2.SendMessageRequest.SerializeToString,
            groups__pb2.SendMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveMessages(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ChatsApp.group.GroupChatService/ReceiveMessages',
            groups__pb2.ReceiveMessageRequest.SerializeToString,
            groups__pb2.ReceiveMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
