# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: groups.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'groups.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cgroups.proto\x12\x0e\x43hatsApp.group\x1a\x0c\x63ommon.proto\"V\n\x12LoadMessageRequest\x12/\n\trequester\x18\x01 \x01(\x0b\x32\x1c.ChatsApp.common.MessageUser\x12\x0f\n\x07groupid\x18\x02 \x01(\x05\"j\n\x13LoadMessageResponse\x12-\n\x07senders\x18\x01 \x03(\x0b\x32\x1c.ChatsApp.common.MessageUser\x12\x10\n\x08messages\x18\x02 \x03(\t\x12\x12\n\ntimestamps\x18\x03 \x03(\t\"\x8a\x01\n\x12SendMessageRequest\x12,\n\x06sender\x18\x01 \x01(\x0b\x32\x1c.ChatsApp.common.MessageUser\x12\x0f\n\x07groupid\x18\x02 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x16\n\tclient_id\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\x0c\n\n_client_id\"i\n\x13SendMessageResponse\x12.\n\x06status\x18\x01 \x01(\x0e\x32\x1e.ChatsApp.common.MessageStatus\x12\x0f\n\x07groupid\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"X\n\x15ReceiveMessageRequest\x12\x0f\n\x07groupid\x18\x01 \x01(\x05\x12\x1b\n\x0elastreceivedid\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x11\n\x0f_lastreceivedid\"\x90\x01\n\x16ReceiveMessageResponse\x12,\n\x06sender\x18\x01 \x01(\x0b\x32\x1c.ChatsApp.common.MessageUser\x12\x10\n\x08group_id\x18\x02 \x01(\x05\x12\x12\n\nmessage_id\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\t2\xad\x02\n\x10GroupChatService\x12W\n\x0cLoadMessages\x12\".ChatsApp.group.LoadMessageRequest\x1a#.ChatsApp.group.LoadMessageResponse\x12Z\n\x0bSendMessage\x12\".ChatsApp.group.SendMessageRequest\x1a#.ChatsApp.group.SendMessageResponse(\x01\x30\x01\x12\x64\n\x0fReceiveMessages\x12%.ChatsApp.group.ReceiveMessageRequest\x1a&.ChatsApp.group.ReceiveMessageResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'groups_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOADMESSAGEREQUEST']._serialized_start=46
  _globals['_LOADMESSAGEREQUEST']._serialized_end=132
  _globals['_LOADMESSAGERESPONSE']._serialized_start=134
  _globals['_LOADMESSAGERESPONSE']._serialized_end=240
  _globals['_SENDMESSAGEREQUEST']._serialized_start=243
  _globals['_SENDMESSAGEREQUEST']._serialized_end=381
  _globals['_SENDMESSAGERESPONSE']._serialized_start=383
  _globals['_SENDMESSAGERESPONSE']._serialized_end=488
  _globals['_RECEIVEMESSAGEREQUEST']._serialized_start=490
  _globals['_RECEIVEMESSAGEREQUEST']._serialized_end=578
  _globals['_RECEIVEMESSAGERESPONSE']._serialized_start=581
  _globals['_RECEIVEMESSAGERESPONSE']._serialized_end=725
  _globals['_GROUPCHATSERVICE']._serialized_start=728
  _globals['_GROUPCHATSERVICE']._serialized_end=1029
# @@protoc_insertion_point(module_scope)
