// source: user.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var common_pb = require('./common_pb.js');
goog.object.extend(proto, common_pb);
goog.exportSymbol('proto.ChatsApp.user.ReceiveMessageRequest', null, global);
goog.exportSymbol('proto.ChatsApp.user.ReceiveMessageResponse', null, global);
goog.exportSymbol('proto.ChatsApp.user.SendMessageRequest', null, global);
goog.exportSymbol('proto.ChatsApp.user.SendMessageResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ChatsApp.user.ReceiveMessageRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ChatsApp.user.ReceiveMessageRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ChatsApp.user.ReceiveMessageRequest.displayName = 'proto.ChatsApp.user.ReceiveMessageRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ChatsApp.user.ReceiveMessageResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ChatsApp.user.ReceiveMessageResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ChatsApp.user.ReceiveMessageResponse.displayName = 'proto.ChatsApp.user.ReceiveMessageResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ChatsApp.user.SendMessageRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ChatsApp.user.SendMessageRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ChatsApp.user.SendMessageRequest.displayName = 'proto.ChatsApp.user.SendMessageRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ChatsApp.user.SendMessageResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ChatsApp.user.SendMessageResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ChatsApp.user.SendMessageResponse.displayName = 'proto.ChatsApp.user.SendMessageResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ChatsApp.user.ReceiveMessageRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.ChatsApp.user.ReceiveMessageRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ChatsApp.user.ReceiveMessageRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ChatsApp.user.ReceiveMessageRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    fromuser: (f = msg.getFromuser()) && common_pb.MessageUser.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ChatsApp.user.ReceiveMessageRequest}
 */
proto.ChatsApp.user.ReceiveMessageRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ChatsApp.user.ReceiveMessageRequest;
  return proto.ChatsApp.user.ReceiveMessageRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ChatsApp.user.ReceiveMessageRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ChatsApp.user.ReceiveMessageRequest}
 */
proto.ChatsApp.user.ReceiveMessageRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new common_pb.MessageUser;
      reader.readMessage(value,common_pb.MessageUser.deserializeBinaryFromReader);
      msg.setFromuser(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ChatsApp.user.ReceiveMessageRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ChatsApp.user.ReceiveMessageRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ChatsApp.user.ReceiveMessageRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ChatsApp.user.ReceiveMessageRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFromuser();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      common_pb.MessageUser.serializeBinaryToWriter
    );
  }
};


/**
 * optional ChatsApp.common.MessageUser fromuser = 1;
 * @return {?proto.ChatsApp.common.MessageUser}
 */
proto.ChatsApp.user.ReceiveMessageRequest.prototype.getFromuser = function() {
  return /** @type{?proto.ChatsApp.common.MessageUser} */ (
    jspb.Message.getWrapperField(this, common_pb.MessageUser, 1));
};


/**
 * @param {?proto.ChatsApp.common.MessageUser|undefined} value
 * @return {!proto.ChatsApp.user.ReceiveMessageRequest} returns this
*/
proto.ChatsApp.user.ReceiveMessageRequest.prototype.setFromuser = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ChatsApp.user.ReceiveMessageRequest} returns this
 */
proto.ChatsApp.user.ReceiveMessageRequest.prototype.clearFromuser = function() {
  return this.setFromuser(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ChatsApp.user.ReceiveMessageRequest.prototype.hasFromuser = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ChatsApp.user.ReceiveMessageResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.ChatsApp.user.ReceiveMessageResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ChatsApp.user.ReceiveMessageResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ChatsApp.user.ReceiveMessageResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    fromuser: (f = msg.getFromuser()) && common_pb.MessageUser.toObject(includeInstance, f),
    textmessage: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ChatsApp.user.ReceiveMessageResponse}
 */
proto.ChatsApp.user.ReceiveMessageResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ChatsApp.user.ReceiveMessageResponse;
  return proto.ChatsApp.user.ReceiveMessageResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ChatsApp.user.ReceiveMessageResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ChatsApp.user.ReceiveMessageResponse}
 */
proto.ChatsApp.user.ReceiveMessageResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new common_pb.MessageUser;
      reader.readMessage(value,common_pb.MessageUser.deserializeBinaryFromReader);
      msg.setFromuser(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTextmessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ChatsApp.user.ReceiveMessageResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ChatsApp.user.ReceiveMessageResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ChatsApp.user.ReceiveMessageResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ChatsApp.user.ReceiveMessageResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFromuser();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      common_pb.MessageUser.serializeBinaryToWriter
    );
  }
  f = message.getTextmessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional ChatsApp.common.MessageUser fromuser = 1;
 * @return {?proto.ChatsApp.common.MessageUser}
 */
proto.ChatsApp.user.ReceiveMessageResponse.prototype.getFromuser = function() {
  return /** @type{?proto.ChatsApp.common.MessageUser} */ (
    jspb.Message.getWrapperField(this, common_pb.MessageUser, 1));
};


/**
 * @param {?proto.ChatsApp.common.MessageUser|undefined} value
 * @return {!proto.ChatsApp.user.ReceiveMessageResponse} returns this
*/
proto.ChatsApp.user.ReceiveMessageResponse.prototype.setFromuser = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ChatsApp.user.ReceiveMessageResponse} returns this
 */
proto.ChatsApp.user.ReceiveMessageResponse.prototype.clearFromuser = function() {
  return this.setFromuser(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ChatsApp.user.ReceiveMessageResponse.prototype.hasFromuser = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string textmessage = 2;
 * @return {string}
 */
proto.ChatsApp.user.ReceiveMessageResponse.prototype.getTextmessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ChatsApp.user.ReceiveMessageResponse} returns this
 */
proto.ChatsApp.user.ReceiveMessageResponse.prototype.setTextmessage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ChatsApp.user.SendMessageRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.ChatsApp.user.SendMessageRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ChatsApp.user.SendMessageRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ChatsApp.user.SendMessageRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    fromuser: (f = msg.getFromuser()) && common_pb.MessageUser.toObject(includeInstance, f),
    touser: (f = msg.getTouser()) && common_pb.MessageUser.toObject(includeInstance, f),
    textmessage: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ChatsApp.user.SendMessageRequest}
 */
proto.ChatsApp.user.SendMessageRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ChatsApp.user.SendMessageRequest;
  return proto.ChatsApp.user.SendMessageRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ChatsApp.user.SendMessageRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ChatsApp.user.SendMessageRequest}
 */
proto.ChatsApp.user.SendMessageRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new common_pb.MessageUser;
      reader.readMessage(value,common_pb.MessageUser.deserializeBinaryFromReader);
      msg.setFromuser(value);
      break;
    case 2:
      var value = new common_pb.MessageUser;
      reader.readMessage(value,common_pb.MessageUser.deserializeBinaryFromReader);
      msg.setTouser(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTextmessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ChatsApp.user.SendMessageRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ChatsApp.user.SendMessageRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ChatsApp.user.SendMessageRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ChatsApp.user.SendMessageRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFromuser();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      common_pb.MessageUser.serializeBinaryToWriter
    );
  }
  f = message.getTouser();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      common_pb.MessageUser.serializeBinaryToWriter
    );
  }
  f = message.getTextmessage();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional ChatsApp.common.MessageUser fromuser = 1;
 * @return {?proto.ChatsApp.common.MessageUser}
 */
proto.ChatsApp.user.SendMessageRequest.prototype.getFromuser = function() {
  return /** @type{?proto.ChatsApp.common.MessageUser} */ (
    jspb.Message.getWrapperField(this, common_pb.MessageUser, 1));
};


/**
 * @param {?proto.ChatsApp.common.MessageUser|undefined} value
 * @return {!proto.ChatsApp.user.SendMessageRequest} returns this
*/
proto.ChatsApp.user.SendMessageRequest.prototype.setFromuser = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ChatsApp.user.SendMessageRequest} returns this
 */
proto.ChatsApp.user.SendMessageRequest.prototype.clearFromuser = function() {
  return this.setFromuser(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ChatsApp.user.SendMessageRequest.prototype.hasFromuser = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional ChatsApp.common.MessageUser touser = 2;
 * @return {?proto.ChatsApp.common.MessageUser}
 */
proto.ChatsApp.user.SendMessageRequest.prototype.getTouser = function() {
  return /** @type{?proto.ChatsApp.common.MessageUser} */ (
    jspb.Message.getWrapperField(this, common_pb.MessageUser, 2));
};


/**
 * @param {?proto.ChatsApp.common.MessageUser|undefined} value
 * @return {!proto.ChatsApp.user.SendMessageRequest} returns this
*/
proto.ChatsApp.user.SendMessageRequest.prototype.setTouser = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ChatsApp.user.SendMessageRequest} returns this
 */
proto.ChatsApp.user.SendMessageRequest.prototype.clearTouser = function() {
  return this.setTouser(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ChatsApp.user.SendMessageRequest.prototype.hasTouser = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string textmessage = 3;
 * @return {string}
 */
proto.ChatsApp.user.SendMessageRequest.prototype.getTextmessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.ChatsApp.user.SendMessageRequest} returns this
 */
proto.ChatsApp.user.SendMessageRequest.prototype.setTextmessage = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ChatsApp.user.SendMessageResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.ChatsApp.user.SendMessageResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ChatsApp.user.SendMessageResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ChatsApp.user.SendMessageResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    response: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ChatsApp.user.SendMessageResponse}
 */
proto.ChatsApp.user.SendMessageResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ChatsApp.user.SendMessageResponse;
  return proto.ChatsApp.user.SendMessageResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ChatsApp.user.SendMessageResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ChatsApp.user.SendMessageResponse}
 */
proto.ChatsApp.user.SendMessageResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.ChatsApp.common.MessageResponseStatus} */ (reader.readEnum());
      msg.setResponse(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ChatsApp.user.SendMessageResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ChatsApp.user.SendMessageResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ChatsApp.user.SendMessageResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ChatsApp.user.SendMessageResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResponse();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
};


/**
 * optional ChatsApp.common.MessageResponseStatus response = 1;
 * @return {!proto.ChatsApp.common.MessageResponseStatus}
 */
proto.ChatsApp.user.SendMessageResponse.prototype.getResponse = function() {
  return /** @type {!proto.ChatsApp.common.MessageResponseStatus} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.ChatsApp.common.MessageResponseStatus} value
 * @return {!proto.ChatsApp.user.SendMessageResponse} returns this
 */
proto.ChatsApp.user.SendMessageResponse.prototype.setResponse = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


goog.object.extend(exports, proto.ChatsApp.user);
