# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\rChatsApp.user\x1a\x0c\x63ommon.proto\"G\n\x15ReceiveMessageRequest\x12.\n\x08\x66romuser\x18\x01 \x01(\x0b\x32\x1c.ChatsApp.common.MessageUser\"]\n\x16ReceiveMessageResponse\x12.\n\x08\x66romuser\x18\x01 \x01(\x0b\x32\x1c.ChatsApp.common.MessageUser\x12\x13\n\x0btextmessage\x18\x02 \x01(\t\"\x87\x01\n\x12SendMessageRequest\x12.\n\x08\x66romuser\x18\x01 \x01(\x0b\x32\x1c.ChatsApp.common.MessageUser\x12,\n\x06touser\x18\x02 \x01(\x0b\x32\x1c.ChatsApp.common.MessageUser\x12\x13\n\x0btextmessage\x18\x03 \x01(\t\"O\n\x13SendMessageResponse\x12\x38\n\x08response\x18\x01 \x01(\x0e\x32&.ChatsApp.common.MessageResponseStatus2\xd6\x01\n\x0fUserChatService\x12\\\n\x0fSendUserMessage\x12!.ChatsApp.user.SendMessageRequest\x1a\".ChatsApp.user.SendMessageResponse(\x01\x30\x01\x12\x65\n\x12ReceiveUserMessage\x12$.ChatsApp.user.ReceiveMessageRequest\x1a%.ChatsApp.user.ReceiveMessageResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECEIVEMESSAGEREQUEST']._serialized_start=43
  _globals['_RECEIVEMESSAGEREQUEST']._serialized_end=114
  _globals['_RECEIVEMESSAGERESPONSE']._serialized_start=116
  _globals['_RECEIVEMESSAGERESPONSE']._serialized_end=209
  _globals['_SENDMESSAGEREQUEST']._serialized_start=212
  _globals['_SENDMESSAGEREQUEST']._serialized_end=347
  _globals['_SENDMESSAGERESPONSE']._serialized_start=349
  _globals['_SENDMESSAGERESPONSE']._serialized_end=428
  _globals['_USERCHATSERVICE']._serialized_start=431
  _globals['_USERCHATSERVICE']._serialized_end=645
# @@protoc_insertion_point(module_scope)
