# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/auth.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'Proto/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Proto import common_pb2 as Proto_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10Proto/auth.proto\x12\rChatsApp.auth\x1a\x12Proto/common.proto\"Q\n\x14\x43reateAccountRequest\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\":\n\x13LoginAccountRequest\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\xa5\x01\n\x15\x43reateAccountResponse\x12/\n\x06status\x18\x01 \x01(\x0e\x32\x1f.ChatsApp.common.ResponseStatus\x12%\n\x06myself\x18\x02 \x01(\x0b\x32\x15.ChatsApp.common.User\x12\'\n\x08\x63ontacts\x18\x03 \x03(\x0b\x32\x15.ChatsApp.common.User\x12\x0b\n\x03url\x18\x04 \x01(\t\"\xa4\x01\n\x14LoginAccountResponse\x12/\n\x06status\x18\x01 \x01(\x0e\x32\x1f.ChatsApp.common.ResponseStatus\x12%\n\x06myself\x18\x02 \x01(\x0b\x32\x15.ChatsApp.common.User\x12\'\n\x08\x63ontacts\x18\x03 \x03(\x0b\x32\x15.ChatsApp.common.User\x12\x0b\n\x03url\x18\x04 \x01(\t2\xc5\x01\n\x0e\x41\x63\x63ountService\x12Z\n\rCreateAccount\x12#.ChatsApp.auth.CreateAccountRequest\x1a$.ChatsApp.auth.CreateAccountResponse\x12W\n\x0cLoginAccount\x12\".ChatsApp.auth.LoginAccountRequest\x1a#.ChatsApp.auth.LoginAccountResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Proto.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEACCOUNTREQUEST']._serialized_start=55
  _globals['_CREATEACCOUNTREQUEST']._serialized_end=136
  _globals['_LOGINACCOUNTREQUEST']._serialized_start=138
  _globals['_LOGINACCOUNTREQUEST']._serialized_end=196
  _globals['_CREATEACCOUNTRESPONSE']._serialized_start=199
  _globals['_CREATEACCOUNTRESPONSE']._serialized_end=364
  _globals['_LOGINACCOUNTRESPONSE']._serialized_start=367
  _globals['_LOGINACCOUNTRESPONSE']._serialized_end=531
  _globals['_ACCOUNTSERVICE']._serialized_start=534
  _globals['_ACCOUNTSERVICE']._serialized_end=731
# @@protoc_insertion_point(module_scope)
